/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThoughtsIndexRouteImport } from './routes/thoughts/index'
import { Route as ThoughtsNewIndexRouteImport } from './routes/thoughts/new/index'
import { Route as ThoughtsThoughtIdIndexRouteImport } from './routes/thoughts/$thoughtId/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as ThoughtsThoughtIdEditRouteImport } from './routes/thoughts/$thoughtId/edit'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsIndexRoute = ThoughtsIndexRouteImport.update({
  id: '/thoughts/',
  path: '/thoughts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsNewIndexRoute = ThoughtsNewIndexRouteImport.update({
  id: '/thoughts/new/',
  path: '/thoughts/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsThoughtIdIndexRoute = ThoughtsThoughtIdIndexRouteImport.update({
  id: '/thoughts/$thoughtId/',
  path: '/thoughts/$thoughtId/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const ThoughtsThoughtIdEditRoute = ThoughtsThoughtIdEditRouteImport.update({
  id: '/thoughts/$thoughtId/edit',
  path: '/thoughts/$thoughtId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thoughts/': typeof ThoughtsIndexRoute
  '/thoughts/$thoughtId/edit': typeof ThoughtsThoughtIdEditRoute
  '/login/': typeof authLoginIndexRoute
  '/register/': typeof authRegisterIndexRoute
  '/thoughts/$thoughtId/': typeof ThoughtsThoughtIdIndexRoute
  '/thoughts/new/': typeof ThoughtsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thoughts': typeof ThoughtsIndexRoute
  '/thoughts/$thoughtId/edit': typeof ThoughtsThoughtIdEditRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/thoughts/$thoughtId': typeof ThoughtsThoughtIdIndexRoute
  '/thoughts/new': typeof ThoughtsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/thoughts/': typeof ThoughtsIndexRoute
  '/thoughts/$thoughtId/edit': typeof ThoughtsThoughtIdEditRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/thoughts/$thoughtId/': typeof ThoughtsThoughtIdIndexRoute
  '/thoughts/new/': typeof ThoughtsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/thoughts/'
    | '/thoughts/$thoughtId/edit'
    | '/login/'
    | '/register/'
    | '/thoughts/$thoughtId/'
    | '/thoughts/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/thoughts'
    | '/thoughts/$thoughtId/edit'
    | '/login'
    | '/register'
    | '/thoughts/$thoughtId'
    | '/thoughts/new'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/thoughts/'
    | '/thoughts/$thoughtId/edit'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/thoughts/$thoughtId/'
    | '/thoughts/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  ThoughtsIndexRoute: typeof ThoughtsIndexRoute
  ThoughtsThoughtIdEditRoute: typeof ThoughtsThoughtIdEditRoute
  ThoughtsThoughtIdIndexRoute: typeof ThoughtsThoughtIdIndexRoute
  ThoughtsNewIndexRoute: typeof ThoughtsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/': {
      id: '/thoughts/'
      path: '/thoughts'
      fullPath: '/thoughts/'
      preLoaderRoute: typeof ThoughtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/new/': {
      id: '/thoughts/new/'
      path: '/thoughts/new'
      fullPath: '/thoughts/new/'
      preLoaderRoute: typeof ThoughtsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/$thoughtId/': {
      id: '/thoughts/$thoughtId/'
      path: '/thoughts/$thoughtId'
      fullPath: '/thoughts/$thoughtId/'
      preLoaderRoute: typeof ThoughtsThoughtIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/thoughts/$thoughtId/edit': {
      id: '/thoughts/$thoughtId/edit'
      path: '/thoughts/$thoughtId/edit'
      fullPath: '/thoughts/$thoughtId/edit'
      preLoaderRoute: typeof ThoughtsThoughtIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  ThoughtsIndexRoute: ThoughtsIndexRoute,
  ThoughtsThoughtIdEditRoute: ThoughtsThoughtIdEditRoute,
  ThoughtsThoughtIdIndexRoute: ThoughtsThoughtIdIndexRoute,
  ThoughtsNewIndexRoute: ThoughtsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
